"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateAccountRequest(google.protobuf.message.Message):
    """Account Management Messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    """Client should hash password before sending"""
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password", "username", b"username"]) -> None: ...

global___CreateAccountRequest = CreateAccountRequest

@typing.final
class CreateAccountResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "success", b"success"]) -> None: ...

global___CreateAccountResponse = CreateAccountResponse

@typing.final
class LoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    """Client should hash password before sending"""
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password", "username", b"username"]) -> None: ...

global___LoginRequest = LoginRequest

@typing.final
class LoginResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    UNREAD_MESSAGE_COUNT_FIELD_NUMBER: builtins.int
    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    unread_message_count: builtins.int
    session_token: builtins.str
    """Token for subsequent requests"""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        unread_message_count: builtins.int = ...,
        session_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "session_token", b"session_token", "success", b"success", "unread_message_count", b"unread_message_count"]) -> None: ...

global___LoginResponse = LoginResponse

@typing.final
class ListAccountsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATTERN_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_NUMBER_FIELD_NUMBER: builtins.int
    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    pattern: builtins.str
    """Wildcard pattern for filtering accounts"""
    page_size: builtins.int
    page_number: builtins.int
    session_token: builtins.str
    def __init__(
        self,
        *,
        pattern: builtins.str = ...,
        page_size: builtins.int = ...,
        page_number: builtins.int = ...,
        session_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_number", b"page_number", "page_size", b"page_size", "pattern", b"pattern", "session_token", b"session_token"]) -> None: ...

global___ListAccountsRequest = ListAccountsRequest

@typing.final
class ListAccountsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTS_FIELD_NUMBER: builtins.int
    HAS_MORE_FIELD_NUMBER: builtins.int
    TOTAL_COUNT_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    has_more: builtins.bool
    total_count: builtins.int
    error_message: builtins.str
    @property
    def accounts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AccountInfo]: ...
    def __init__(
        self,
        *,
        accounts: collections.abc.Iterable[global___AccountInfo] | None = ...,
        has_more: builtins.bool = ...,
        total_count: builtins.int = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accounts", b"accounts", "error_message", b"error_message", "has_more", b"has_more", "total_count", b"total_count"]) -> None: ...

global___ListAccountsResponse = ListAccountsResponse

@typing.final
class AccountInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    IS_ONLINE_FIELD_NUMBER: builtins.int
    username: builtins.str
    is_online: builtins.bool
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        is_online: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["is_online", b"is_online", "username", b"username"]) -> None: ...

global___AccountInfo = AccountInfo

@typing.final
class DeleteAccountRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    session_token: builtins.str
    def __init__(
        self,
        *,
        session_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_token", b"session_token"]) -> None: ...

global___DeleteAccountRequest = DeleteAccountRequest

@typing.final
class DeleteAccountResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "success", b"success"]) -> None: ...

global___DeleteAccountResponse = DeleteAccountResponse

@typing.final
class SendMessageRequest(google.protobuf.message.Message):
    """Messaging Messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECIPIENT_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    recipient: builtins.str
    content: builtins.str
    session_token: builtins.str
    def __init__(
        self,
        *,
        recipient: builtins.str = ...,
        content: builtins.str = ...,
        session_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "recipient", b"recipient", "session_token", b"session_token"]) -> None: ...

global___SendMessageRequest = SendMessageRequest

@typing.final
class SendMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    MESSAGE_ID_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    message_id: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        message_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "message_id", b"message_id", "success", b"success"]) -> None: ...

global___SendMessageResponse = SendMessageResponse

@typing.final
class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    SENDER_FIELD_NUMBER: builtins.int
    RECIPIENT_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    DELIVERED_FIELD_NUMBER: builtins.int
    UNREAD_FIELD_NUMBER: builtins.int
    DELETED_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    sender: builtins.str
    recipient: builtins.str
    content: builtins.str
    timestamp: builtins.int
    delivered: builtins.bool
    unread: builtins.bool
    deleted: builtins.bool
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
        sender: builtins.str = ...,
        recipient: builtins.str = ...,
        content: builtins.str = ...,
        timestamp: builtins.int = ...,
        delivered: builtins.bool = ...,
        unread: builtins.bool = ...,
        deleted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "deleted", b"deleted", "delivered", b"delivered", "message_id", b"message_id", "recipient", b"recipient", "sender", b"sender", "timestamp", b"timestamp", "unread", b"unread"]) -> None: ...

global___Message = Message

@typing.final
class GetMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAX_MESSAGES_FIELD_NUMBER: builtins.int
    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    max_messages: builtins.int
    """Number of messages to retrieve"""
    session_token: builtins.str
    def __init__(
        self,
        *,
        max_messages: builtins.int = ...,
        session_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_messages", b"max_messages", "session_token", b"session_token"]) -> None: ...

global___GetMessagesRequest = GetMessagesRequest

@typing.final
class GetMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: builtins.int
    HAS_MORE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    has_more: builtins.bool
    error_message: builtins.str
    @property
    def messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Message]: ...
    def __init__(
        self,
        *,
        messages: collections.abc.Iterable[global___Message] | None = ...,
        has_more: builtins.bool = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "has_more", b"has_more", "messages", b"messages"]) -> None: ...

global___GetMessagesResponse = GetMessagesResponse

@typing.final
class DeleteMessagesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_IDS_FIELD_NUMBER: builtins.int
    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    session_token: builtins.str
    @property
    def message_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        message_ids: collections.abc.Iterable[builtins.str] | None = ...,
        session_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message_ids", b"message_ids", "session_token", b"session_token"]) -> None: ...

global___DeleteMessagesRequest = DeleteMessagesRequest

@typing.final
class DeleteMessagesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    FAILED_MESSAGE_IDS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    @property
    def failed_message_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """IDs of messages that couldn't be deleted"""

    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        failed_message_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "failed_message_ids", b"failed_message_ids", "success", b"success"]) -> None: ...

global___DeleteMessagesResponse = DeleteMessagesResponse

@typing.final
class LogoutRequest(google.protobuf.message.Message):
    """Logout message definitions"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    session_token: builtins.str
    def __init__(
        self,
        *,
        session_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_token", b"session_token"]) -> None: ...

global___LogoutRequest = LogoutRequest

@typing.final
class LogoutResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "success", b"success"]) -> None: ...

global___LogoutResponse = LogoutResponse

@typing.final
class MarkConversationAsReadRequest(google.protobuf.message.Message):
    """Mark conversation as read"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_TOKEN_FIELD_NUMBER: builtins.int
    OTHER_USER_FIELD_NUMBER: builtins.int
    session_token: builtins.str
    other_user: builtins.str
    """The other user in the conversation"""
    def __init__(
        self,
        *,
        session_token: builtins.str = ...,
        other_user: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["other_user", b"other_user", "session_token", b"session_token"]) -> None: ...

global___MarkConversationAsReadRequest = MarkConversationAsReadRequest

@typing.final
class MarkConversationAsReadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "success", b"success"]) -> None: ...

global___MarkConversationAsReadResponse = MarkConversationAsReadResponse
