"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ReplicaInfo(google.protobuf.message.Message):
    """Information about a replica in the cluster"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPLICA_ID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    CURRENT_SEQUENCE_FIELD_NUMBER: builtins.int
    LAST_APPLIED_SEQUENCE_FIELD_NUMBER: builtins.int
    IS_LEADER_FIELD_NUMBER: builtins.int
    LAST_HEARTBEAT_FIELD_NUMBER: builtins.int
    replica_id: builtins.str
    address: builtins.str
    role: builtins.str
    current_sequence: builtins.int
    last_applied_sequence: builtins.int
    is_leader: builtins.bool
    last_heartbeat: builtins.int
    def __init__(
        self,
        *,
        replica_id: builtins.str = ...,
        address: builtins.str = ...,
        role: builtins.str = ...,
        current_sequence: builtins.int = ...,
        last_applied_sequence: builtins.int = ...,
        is_leader: builtins.bool = ...,
        last_heartbeat: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "current_sequence", b"current_sequence", "is_leader", b"is_leader", "last_applied_sequence", b"last_applied_sequence", "last_heartbeat", b"last_heartbeat", "replica_id", b"replica_id", "role", b"role"]) -> None: ...

global___ReplicaInfo = ReplicaInfo

@typing.final
class ReplicatedRequest(google.protobuf.message.Message):
    """Wrapper for all client requests that need replication"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    COORDINATOR_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    sequence_number: builtins.int
    operation: builtins.str
    """Name of the original gRPC method"""
    payload: builtins.bytes
    """Serialized original request"""
    coordinator_id: builtins.str
    timestamp: builtins.int
    def __init__(
        self,
        *,
        sequence_number: builtins.int = ...,
        operation: builtins.str = ...,
        payload: builtins.bytes = ...,
        coordinator_id: builtins.str = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coordinator_id", b"coordinator_id", "operation", b"operation", "payload", b"payload", "sequence_number", b"sequence_number", "timestamp", b"timestamp"]) -> None: ...

global___ReplicatedRequest = ReplicatedRequest

@typing.final
class ReplicatedResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    result: builtins.bytes
    """Serialized original response"""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        result: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "result", b"result", "success", b"success"]) -> None: ...

global___ReplicatedResponse = ReplicatedResponse

@typing.final
class Ack(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    REPLICA_ID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    sequence_number: builtins.int
    replica_id: builtins.str
    success: builtins.bool
    error_message: builtins.str
    def __init__(
        self,
        *,
        sequence_number: builtins.int = ...,
        replica_id: builtins.str = ...,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "replica_id", b"replica_id", "sequence_number", b"sequence_number", "success", b"success"]) -> None: ...

global___Ack = Ack

@typing.final
class HeartbeatRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COORDINATOR_ID_FIELD_NUMBER: builtins.int
    SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    coordinator_id: builtins.str
    sequence_number: builtins.int
    timestamp: builtins.int
    def __init__(
        self,
        *,
        coordinator_id: builtins.str = ...,
        sequence_number: builtins.int = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["coordinator_id", b"coordinator_id", "sequence_number", b"sequence_number", "timestamp", b"timestamp"]) -> None: ...

global___HeartbeatRequest = HeartbeatRequest

@typing.final
class HeartbeatResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    REPLICA_ID_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    CURRENT_SEQUENCE_FIELD_NUMBER: builtins.int
    LAST_APPLIED_SEQUENCE_FIELD_NUMBER: builtins.int
    IS_LEADER_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    replica_id: builtins.str
    role: builtins.str
    current_sequence: builtins.int
    last_applied_sequence: builtins.int
    is_leader: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        replica_id: builtins.str = ...,
        role: builtins.str = ...,
        current_sequence: builtins.int = ...,
        last_applied_sequence: builtins.int = ...,
        is_leader: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["current_sequence", b"current_sequence", "error_message", b"error_message", "is_leader", b"is_leader", "last_applied_sequence", b"last_applied_sequence", "replica_id", b"replica_id", "role", b"role", "success", b"success"]) -> None: ...

global___HeartbeatResponse = HeartbeatResponse

@typing.final
class JoinClusterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPLICA_ID_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    LAST_APPLIED_SEQUENCE_FIELD_NUMBER: builtins.int
    replica_id: builtins.str
    address: builtins.str
    last_applied_sequence: builtins.int
    def __init__(
        self,
        *,
        replica_id: builtins.str = ...,
        address: builtins.str = ...,
        last_applied_sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "last_applied_sequence", b"last_applied_sequence", "replica_id", b"replica_id"]) -> None: ...

global___JoinClusterRequest = JoinClusterRequest

@typing.final
class JoinClusterResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    MISSING_OPERATIONS_FIELD_NUMBER: builtins.int
    CURRENT_SEQUENCE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    current_sequence: builtins.int
    @property
    def missing_operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ReplicatedRequest]: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        missing_operations: collections.abc.Iterable[global___ReplicatedRequest] | None = ...,
        current_sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["current_sequence", b"current_sequence", "error_message", b"error_message", "missing_operations", b"missing_operations", "success", b"success"]) -> None: ...

global___JoinClusterResponse = JoinClusterResponse

@typing.final
class RequestMissingOpsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPLICA_ID_FIELD_NUMBER: builtins.int
    FROM_SEQUENCE_FIELD_NUMBER: builtins.int
    TO_SEQUENCE_FIELD_NUMBER: builtins.int
    replica_id: builtins.str
    from_sequence: builtins.int
    to_sequence: builtins.int
    def __init__(
        self,
        *,
        replica_id: builtins.str = ...,
        from_sequence: builtins.int = ...,
        to_sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["from_sequence", b"from_sequence", "replica_id", b"replica_id", "to_sequence", b"to_sequence"]) -> None: ...

global___RequestMissingOpsRequest = RequestMissingOpsRequest

@typing.final
class RequestMissingOpsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    OPERATIONS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    @property
    def operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ReplicatedRequest]: ...
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        operations: collections.abc.Iterable[global___ReplicatedRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "operations", b"operations", "success", b"success"]) -> None: ...

global___RequestMissingOpsResponse = RequestMissingOpsResponse

@typing.final
class ElectLeaderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CANDIDATE_ID_FIELD_NUMBER: builtins.int
    LAST_APPLIED_SEQUENCE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    candidate_id: builtins.str
    last_applied_sequence: builtins.int
    timestamp: builtins.int
    def __init__(
        self,
        *,
        candidate_id: builtins.str = ...,
        last_applied_sequence: builtins.int = ...,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["candidate_id", b"candidate_id", "last_applied_sequence", b"last_applied_sequence", "timestamp", b"timestamp"]) -> None: ...

global___ElectLeaderRequest = ElectLeaderRequest

@typing.final
class ElectLeaderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    ELECTED_LEADER_ID_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    elected_leader_id: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        elected_leader_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["elected_leader_id", b"elected_leader_id", "error_message", b"error_message", "success", b"success"]) -> None: ...

global___ElectLeaderResponse = ElectLeaderResponse

@typing.final
class FindLeaderRequest(google.protobuf.message.Message):
    """Find leader request/response"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: builtins.int
    client_id: builtins.str
    def __init__(
        self,
        *,
        client_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_id", b"client_id"]) -> None: ...

global___FindLeaderRequest = FindLeaderRequest

@typing.final
class FindLeaderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    LEADER_ID_FIELD_NUMBER: builtins.int
    LEADER_ADDRESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    error_message: builtins.str
    leader_id: builtins.str
    leader_address: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        leader_id: builtins.str = ...,
        leader_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message", "leader_address", b"leader_address", "leader_id", b"leader_id", "success", b"success"]) -> None: ...

global___FindLeaderResponse = FindLeaderResponse
