# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationServiceStub(object):
    """Replication service for handling replicated requests and coordination
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleClientRequest = channel.unary_unary(
                '/replication.ReplicationService/HandleClientRequest',
                request_serializer=replication__pb2.ReplicatedRequest.SerializeToString,
                response_deserializer=replication__pb2.ReplicatedResponse.FromString,
                _registered_method=True)
        self.FindLeader = channel.unary_unary(
                '/replication.ReplicationService/FindLeader',
                request_serializer=replication__pb2.FindLeaderRequest.SerializeToString,
                response_deserializer=replication__pb2.FindLeaderResponse.FromString,
                _registered_method=True)
        self.ReplicateRequest = channel.unary_unary(
                '/replication.ReplicationService/ReplicateRequest',
                request_serializer=replication__pb2.ReplicatedRequest.SerializeToString,
                response_deserializer=replication__pb2.Ack.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/replication.ReplicationService/Heartbeat',
                request_serializer=replication__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=replication__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.JoinCluster = channel.unary_unary(
                '/replication.ReplicationService/JoinCluster',
                request_serializer=replication__pb2.JoinClusterRequest.SerializeToString,
                response_deserializer=replication__pb2.JoinClusterResponse.FromString,
                _registered_method=True)
        self.RequestMissingOps = channel.unary_unary(
                '/replication.ReplicationService/RequestMissingOps',
                request_serializer=replication__pb2.RequestMissingOpsRequest.SerializeToString,
                response_deserializer=replication__pb2.RequestMissingOpsResponse.FromString,
                _registered_method=True)
        self.ElectLeader = channel.unary_unary(
                '/replication.ReplicationService/ElectLeader',
                request_serializer=replication__pb2.ElectLeaderRequest.SerializeToString,
                response_deserializer=replication__pb2.ElectLeaderResponse.FromString,
                _registered_method=True)


class ReplicationServiceServicer(object):
    """Replication service for handling replicated requests and coordination
    """

    def HandleClientRequest(self, request, context):
        """Client-facing RPCs (only handled by coordinator)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateRequest(self, request, context):
        """Replica-to-replica RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestMissingOps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleClientRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleClientRequest,
                    request_deserializer=replication__pb2.ReplicatedRequest.FromString,
                    response_serializer=replication__pb2.ReplicatedResponse.SerializeToString,
            ),
            'FindLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.FindLeader,
                    request_deserializer=replication__pb2.FindLeaderRequest.FromString,
                    response_serializer=replication__pb2.FindLeaderResponse.SerializeToString,
            ),
            'ReplicateRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateRequest,
                    request_deserializer=replication__pb2.ReplicatedRequest.FromString,
                    response_serializer=replication__pb2.Ack.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=replication__pb2.HeartbeatRequest.FromString,
                    response_serializer=replication__pb2.HeartbeatResponse.SerializeToString,
            ),
            'JoinCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinCluster,
                    request_deserializer=replication__pb2.JoinClusterRequest.FromString,
                    response_serializer=replication__pb2.JoinClusterResponse.SerializeToString,
            ),
            'RequestMissingOps': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMissingOps,
                    request_deserializer=replication__pb2.RequestMissingOpsRequest.FromString,
                    response_serializer=replication__pb2.RequestMissingOpsResponse.SerializeToString,
            ),
            'ElectLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectLeader,
                    request_deserializer=replication__pb2.ElectLeaderRequest.FromString,
                    response_serializer=replication__pb2.ElectLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.ReplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.ReplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicationService(object):
    """Replication service for handling replicated requests and coordination
    """

    @staticmethod
    def HandleClientRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/HandleClientRequest',
            replication__pb2.ReplicatedRequest.SerializeToString,
            replication__pb2.ReplicatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/FindLeader',
            replication__pb2.FindLeaderRequest.SerializeToString,
            replication__pb2.FindLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/ReplicateRequest',
            replication__pb2.ReplicatedRequest.SerializeToString,
            replication__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/Heartbeat',
            replication__pb2.HeartbeatRequest.SerializeToString,
            replication__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/JoinCluster',
            replication__pb2.JoinClusterRequest.SerializeToString,
            replication__pb2.JoinClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestMissingOps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/RequestMissingOps',
            replication__pb2.RequestMissingOpsRequest.SerializeToString,
            replication__pb2.RequestMissingOpsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ElectLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.ReplicationService/ElectLeader',
            replication__pb2.ElectLeaderRequest.SerializeToString,
            replication__pb2.ElectLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
